<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>Multiside</AssemblyName>
    <RootNamespace>Multiside</RootNamespace>
	<ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Multiside.shared\Multiside.shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\dependencies\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Common">
      <HintPath>..\dependencies\Il2CppInterop.Common.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>..\dependencies\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\dependencies\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>..\dependencies\MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\dependencies\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="PhotonChat">
      <HintPath>..\dependencies\PhotonChat.dll</HintPath>
    </Reference>
    <Reference Include="PhotonClient">
      <HintPath>..\dependencies\PhotonClient.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>..\dependencies\PhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\dependencies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\dependencies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\dependencies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>