<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>..\..\00_MSZ_DLLS\0.72\UnityEngine.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>